server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: dfsdfs$erf2
    key-store-type: JKS
    key-alias: myalias

    trust-store: classpath:truststore.jks
    trust-store-password: wqewe34234+ewr
    trust-store-type: JKS
